version: '3'
services:
  local-db:
    platform: linux/x86_64
    image: library/mysql:5.7
    container_name: local-db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: akqlshrl789
      TZ: Asia/Seoul